variables:
  GIT_STRATEGY: fetch
  GIT_SSL_NO_VERIFY: "true"
  GIT_LFS_SKIP_SMUDGE: 1
  PROJECT_SCRIPT: src/run_workflow.py

stages:
  - build
  - update

image_build:
  stage: build
  image: docker:stable
  rules:
    - if: '$CI_PIPELINE_SOURCE != "pipeline" && $CI_UPSTREAM_PROJECT != "omnibenchmark/{{ benchmark_name }}/orchestrator-py"'
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN http://$CI_REGISTRY
  script: |
    CI_COMMIT_SHA_7=$(echo $CI_COMMIT_SHA | cut -c1-7)
    docker build --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA_7 .
    docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA_7

update_build:
  stage: build
  image: docker:stable
  rules:
    - if: '$CI_PIPELINE_SOURCE == "pipeline" && $CI_UPSTREAM_PROJECT == "omnibenchmark/{{ benchmark_name }}/orchestrator-py"'
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN http://$CI_REGISTRY
  script: |
    docker build --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

run_udpate:
  stage: update
  image: 
    name: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    entrypoint: [""]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "pipeline" && $CI_UPSTREAM_PROJECT == "omnibenchmark/{{ benchmark_name }}/orchestrator-py"'
  before_script:
  {% if username %}
    - git config --global user.name "{{ username }}"
  {% else %}
    - git config --global user.name "USERNAME"
  {% endif %}
  {% if mail_address %}
    - git config --global user.email "{{ mail_address }}"
  {% else %}
    - git config --global user.email "MAIL ADDRESS"
  {% endif %}
    - git config --global --add safe.directory /builds/gitlab/omnibenchmark/{{ benchmark_name }}/{{__sanitized_project_name}}
    - url_host=`git remote get-url origin | sed -e "s/https:\/\/gitlab-ci-token:.*@//g"`
    - cd /tmp/
    - git clone "https://oauth2:${CI_PUSH_TOKEN}@${url_host}"
    - cd ${CI_PROJECT_NAME}
    - chmod +x ./$PROJECT_SCRIPT
    - git lfs install --local
  script:
    - python $PROJECT_SCRIPT
    - 'renku graph export --full --strict > graph.json'
    - 'curl -u  "omni_update:${OMNI_UPDATE_TOKEN}" -i -X  POST "http://imlspenticton.uzh.ch/{{ benchmark_name }}_data" -H "Content-Type:application/ld+json" -d "@graph.json"'
