---
data:
    name: "{{__sanitized_project_name__}}"
    title: "{{ project_title }}"
    description: "{{ project_description }}"
    keywords: ["{{ processed_keyword }}"]
script: "src/{{__sanitized_project_name__}}.R" ## change this to .py if you are using a py script
inputs:
    keywords: ["INPUT_KEY1", "INPUT_KEY2"]
    files: ["input_file_name1", "input_file_name2"]
    prefix:
        input_file_name1: "_INPUT1_"
        input_file_name2: "_INPUT2_"
        # ...
outputs:
    template: "data/${name}/${name}_${out_name}.${out_end}"
    files:
        data_file1: 
            end: "FILE1_END"
        data_file2:
            end: "FILE2_END"
        # ...
benchmark_name: "{{ benchmark_name }}"
