variables:
  GIT_STRATEGY: fetch
  GIT_SSL_NO_VERIFY: "true"
  GIT_LFS_SKIP_SMUDGE: 1
  PROJECT_SCRIPT: src/run_project.sh 

stages:
  - build
  - update
  - check

image_build:
  stage: build
  image: docker:stable
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN http://$CI_REGISTRY
  script: |
    CI_COMMIT_SHA_7=$(echo $CI_COMMIT_SHA | cut -c1-7)
    docker build --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA_7 .
    docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA_7

update_build:
  stage: build
  image: docker:stable
  rules:
    - if: '$CI_PIPELINE_SOURCE == "pipeline" && $CI_UPSTREAM_PROJECT == "omnibenchmark/orchestrator"'
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN http://$CI_REGISTRY
  script: |
    docker build --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

    
run_udpate:
  stage: update
  image: 
    name: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    entrypoint: [""]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "pipeline" && $CI_UPSTREAM_PROJECT == "omnibenchmark/orchestrator"'
  before_script:
    - git config --global user.name "YOUR_USER_NAME"
    - git config --global user.email "YOUR_MAIL"
    - url_host=`git remote get-url origin | sed -e "s/https:\/\/gitlab-ci-token:.*@//g"`
    - cd /tmp/
    - git clone "https://oauth2:${CI_PUSH_TOKEN}@${url_host}"
    - cd ${CI_PROJECT_NAME}
    - chmod +x ./$PROJECT_SCRIPT
    - git lfs install --local
  script:
    - cd src
    - git clone https://renkulab.io/gitlab/omnibenchmark/utils.git
    - cd ..
    - renku save -m  'Clone submodule'
    - ./$PROJECT_SCRIPT

run_check:
  stage: check
  image: 
    name: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    entrypoint: [""]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "pipeline" && $CI_UPSTREAM_PROJECT == "omnibenchmark/orchestrator"'
  before_script:
    - git config --global user.name "YOUR_USER_NAME"
    - git config --global user.email "YOUR_MAIL"
    - url_host=`git remote get-url origin | sed -e "s/https:\/\/gitlab-ci-token:.*@//g"`
    - cd /tmp/
    - git clone "https://oauth2:${CI_PUSH_TOKEN}@${url_host}"
    - cd ${CI_PROJECT_NAME}
    - git lfs install --local
  script:
    - cd src
    - git clone https://renkulab.io/gitlab/omnibenchmark/utils.git
    - cd ..
    - source src/config.sh
    - source src/utils/import.sh
    - dataset_name=${DATA_VARS['name']}
    - git lfs pull -I data/
    - schema_check_dataset $dataset_name "${TAG_LIST[@]}"
