---
data:
    name: "{{__sanitized_project_name__}}"
    title: "{{ project_title }}"
    description: "{{ project_description }}"
    keywords: ["{{ dataset_keyword }}"]
script: "src/example.R"
outputs:
    template: "data/${name}/${name}_${out_name}.${out_end}"
    files:
        counts: 
            end: "mtx.gz"
        data_info:
            end: "json"
        meta:
            end: "json"
        feature:
            end: "json"
benchmark_name: "{{ benchmark_name }}"
